/**
 * Builds src/data/regionMap.ts — the projected outlines behind the home-page
 * region map — from Natural Earth 1:50m country borders (world-atlas@2).
 *
 * The three packages are not project dependencies; install them ad hoc:
 *
 *   npm i --no-save topojson-client d3-geo world-atlas@2
 *   node scripts/region-map.mjs
 *
 * Served markets are fitted to the frame; neighbours are clipped to it so the
 * output stays small (Italy's boot and the Aegean would otherwise dominate).
 * Serbia is drawn as one shape together with Kosovo, as maps in the region do.
 */
import * as topojson from "topojson-client";
import { geoConicConformal, geoPath } from "d3-geo";
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"));
const geoms = topo.objects.countries.geometries;
const byName = (name) => {
  const g = geoms.find((g) => g.properties.name === name);
  if (!g) throw new Error(`No country named ${name}`);
  return g;
};
const geometry = (name) => topojson.feature(topo, byName(name)).geometry;

const W = 720;
const H = 640;
const PAD = 36;

/** Served markets in the client's order, with the capital each arc runs to. */
const served = [
  { code: "rs", geom: topojson.merge(topo, [byName("Serbia"), byName("Kosovo")]), capital: [20.4569, 44.8176] },
  { code: "me", geom: geometry("Montenegro"), capital: [19.2594, 42.4304] },
  { code: "ba", geom: geometry("Bosnia and Herz."), capital: [18.4131, 43.8563] },
  { code: "si", geom: geometry("Slovenia"), capital: [14.5058, 46.0569] },
  { code: "hr", geom: geometry("Croatia"), capital: [15.9819, 45.815] },
  { code: "mk", geom: geometry("Macedonia"), capital: [21.4254, 41.9981] },
];
const context = ["Italy", "Austria", "Hungary", "Romania", "Bulgaria", "Greece", "Albania", "Slovakia"];

const servedCollection = {
  type: "FeatureCollection",
  features: served.map((s) => ({ type: "Feature", geometry: s.geom })),
};
const projection = geoConicConformal()
  .parallels([41.5, 46.5])
  .rotate([-18.5, 0])
  .fitExtent([[PAD, PAD], [W - PAD, H - PAD]], servedCollection)
  .clipExtent([[-8, -8], [W + 8, H + 8]]);
const path = geoPath(projection).digits(1);
const round = (n) => Math.round(n * 10) / 10;

const servedOut = served.map((s) => ({
  code: s.code,
  d: path(s.geom),
  capital: projection(s.capital).map(round),
}));
const contextOut = context
  .map((name) => ({ code: name.slice(0, 2).toLowerCase(), d: path(geometry(name)) }))
  .filter((c) => c.d);

const ts = `/**
 * Projected outlines for the home-page region map.
 *
 * GENERATED by scripts/region-map.mjs — edit that script, not this file.
 * Natural Earth 1:50m borders, Lambert conformal conic centred on the region,
 * fitted to a ${W}×${H} frame. Serbia is one shape together with Kosovo.
 */
export const regionMapViewBox = "0 0 ${W} ${H}";

export type RegionCode = ${served.map((s) => `"${s.code}"`).join(" | ")};

export type ServedRegion = {
  code: RegionCode;
  d: string;
  /** Capital, in viewBox units — where the arc from Belgrade lands. */
  capital: [number, number];
};

/** Served markets, in display order. */
export const servedRegions: ServedRegion[] = [
${servedOut.map((s) => `  { code: "${s.code}", capital: [${s.capital.join(", ")}], d: "${s.d}" },`).join("\n")}
];

/** Neighbouring countries, drawn faintly for orientation. */
export const contextRegions: { code: string; d: string }[] = [
${contextOut.map((c) => `  { code: "${c.code}", d: "${c.d}" },`).join("\n")}
];
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/data/regionMap.ts");
writeFileSync(out, ts);
console.log(`wrote ${out} (${ts.length} chars)`);
